#!/bin/sh
module="mod_janus"
device="mod_janus"
user="root"
group="root"
mode="666"

# invoke insmod with all arguments we got
/sbin/rmmod $module
/sbin/insmod -f $module || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}
mknod /dev/${device} c $major 0

chown $user  /dev/${device}
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
